const paymentStatus = {
    PENDING: "Pending",
    PENDING_APPROVAL: "Pending Approval",
    OAUTH_CALLBACK_COMPLETE: "OAuth Callback Complete",
    AUTHORISED: "Authorised",
    "SETTLEMENT_PENDING" "SETTLEMENT_IN_PROGRESS" "SETTLEMENT_COMPLETE" "PAYMENT_RECEIVED" "TIMEOUT" "CONSENT_API_REJECTED" "DECLINED" "CONSENT_TIMEOUT" "SETTLEMENT_REJECTED" "UNKNOWN" "UNEXPECTED_ERROR"
}
